language: php
sudo: false

php:
  - 7.1

before_script:
  - composer box-install
  - composer install --no-interaction --no-progress

script:
  - composer box-compile
  - sha1sum drush.phar > drush.version

deploy:
  provider: releases
  api_key:
    secure: L2kB6OGsdb5ac9/EXY5RoTW//ZjspPwRIV8y3FsBjvtChCJiRhCIrKQbIe+agvTUe4aXF6XdhYSHMIRpyRBicyoYfQIw0VgtBm6nYYIBRzJ88kcVsZkHh0X/AmcomG+0aqXry//gpd8MIkslBpQchLWQigHsCYVRuAYKqj/wy4TGLUMwB0wdL8lHC8HUKXcnRizAHOoqPooJcum5edFlZJFRLoapWB44OqSbbMcSsOfRgi4SdoELFd3bQkCG0zc+OwRewtsHuTx7892bNb/dWK2jNdvQ9vnaCJxf6Wlnxu36K5YrE2TjKzgNQKLQmXMA1Xx7xqHb7ZDigp9dVk6TpBhxkrU3Z2/XHvj/F6W7RH2JG1bUjtVnR+K7tG5oOEACMAaFC4NdiCPzeXK1UtgzK0UDJ4WY1ZR62L6PwK2gCsASglTcx+u/iQybWl0gevVLD+HGiXqPC/XjuKQK4F2YZIcZLXloU3Qx1SOFh9tfcH6t44o4fNYVBb5of3PyBLA/seY/j7IWh5kZibQAO23CJTspvO7iSmWqtCr5SNCxjJSzHJscb2WWtvT+pt2i6BhmdBAuzefWgypJOzRG9U38lWg2PyNmpI5c9pe0dCRE11k9ALFuLH+n24lMPKPV8A1kd1a6CdfrND7yf41d6IJgePYgUN5QMG2ZlWPxfK8riyA=
  file:
    - drush.phar
    - drush.version
  on:
    repo: drush-ops/drush-launcher
    tags: true
  skip_cleanup: true
